api_platform:
    # The title of the API.
    title : "API - Let's talk"
    # The description of the API.
    description : "REST API for the Let's talk application"

    collection:
        pagination:
            enabled: false # or true
            items_per_page: 25 # Items number per page
            client_enabled: true # ?pagination=true
            client_items_per_page: true # ?items_per_page=10
            items_per_page_parameter_name: "count" # ?count=10
            enabled_parameter_name: "pagination" # ?/pag=false

    # The version of the API.
    version : "0.1.0"

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
